name: $name
authors: [DrakePork, Redhelmet8]
description: $description
version: $version
main: net.skyprison.skyprisoncore.SkyPrisonCore
api-version: "$apiVersion"
website: https://skyprison.net/
depend: [WorldGuard, WorldEdit, PlaceholderAPI, CMI, Parkour, ShopGUIPlus, CoreProtect, PvPManager, AdvancedRegionMarket]
commands:
  #
  # Minigame Commands
  #
  sponge:
    description: Sponge Commands
    usage: /<command>
    permission: skyprisoncore.command.sponge
    permission-message: §4Error:§c You do not have permission to execute this command...
  #
  # Cheese?
  #
  skyplot:
    description: Opens the skyplot GUI
    usage: /<command>
    permission: skyprisoncore.command.skyplot
    permission-message: §4Error:§c You do not have permission to execute this command...
  plot:
    description: Opens plot TP GUI
    usage: /<command>
    aliases: [plottp, plotteleport]
    permission: skyprisoncore.command.plotteleport
    permission-message: §4Error:§c You do not have permission to execute this command...
  tags:
    description: Tags command
    usage: /<command>
    permission: skyprisoncore.command.tags
    permission-message: §4Error:§c You do not have permission to execute this command...
permissions:
  #
  # Guard Permissions
  #
  skyprisoncore.guard.onduty:
    description: player is on duty when they have this perm
    default: false
  skyprisoncore.showhit:
    description: Shows when a player hits you
  skyprisoncore.contraband.itembypass:
    description: Bypasses Item Removal and that kind of stuff
  #
  # Minigame Permissions
  #
  skyprisoncore.command.sponge:
    description: Gives acess to /sponge
  skyprisoncore.command.skyplot:
    description: Gives access to /skyplot
  skyprisoncore.command.plotteleport:
    description: Gives access to /plot
  skyprisoncore.command.tags:
    description: Gives access to /tags
  skyprisoncore.command.tags.admin:
    description: Gives access to tags stuff
