name: $name
authors: [DrakePork, Redhelmet8]
description: $description
version: $version
main: net.skyprison.skyprisoncore.SkyPrisonCore
api-version: "$apiVersion"
website: https://skyprison.net/
depend: [WorldGuard, WorldEdit, PlaceholderAPI, CMI, Parkour, ShopGUIPlus, CoreProtect, PvPManager, AdvancedRegionMarket, CustomCrafting]
commands:
  ignoretp:
    description: Ignore someones tpa requests
    aliases: [tpignore]
    usage: /<command>
    permission: skyprisoncore.command.ignoretp
    permission-message: §4Error:§c You do not have permission to execute this command...
  #
  # Minigame Commands
  #
  sponge:
    description: Sponge Commands
    usage: /<command>
    permission: skyprisoncore.command.sponge
    permission-message: §4Error:§c You do not have permission to execute this command...
  endupgrade:
    description: Opens the end upgrade GUI
    usage: /<command>
    permission: skyprisoncore.command.endupgrade
    permission-message: §4Error:§c You do not have permission to execute this command...
  #
  # Killinfo Commands
  #
  killinfo:
    description: Shows info about PvP
    usage: /<command>
    aliases: [killsinfo, killstats, pvpstats]
    permission: skyprisoncore.command.killinfo
    permission-message: §4Error:§c You do not have permission to execute this command...
  #
  # Cheese?
  #
  removeitalics:
    description: Removes italics from item
    usage: /<command>
    permission: skyprisoncore.command.removeitalics
    permission-message: §4Error:§c You do not have permission to execute this command...
  daily:
    description: Opens the daily reward GUI
    usage: /<command>
    permission: skyprisoncore.command.daily
    permission-message: §4Error:§c You do not have permission to execute this command...
  skyplot:
    description: Opens the daily reward GUI
    usage: /<command>
    permission: skyprisoncore.command.skyplot
    permission-message: §4Error:§c You do not have permission to execute this command...
  plot:
    description: Opens plot TP GUI
    usage: /<command>
    aliases: [plottp, plotteleport]
    permission: skyprisoncore.command.plotteleport
    permission-message: §4Error:§c You do not have permission to execute this command...
  tags:
    description: Tags command
    usage: /<command>
    permission: skyprisoncore.command.tags
    permission-message: §4Error:§c You do not have permission to execute this command...
  minereset:
    description: Tags command
    usage: /<command>
    permission: skyprisoncore.command.minereset
    permission-message: §4Error:§c You do not have permission to execute this command...
  randomgive:
    description: Randomgive command
    usage: /<command>
    permission: skyprisoncore.command.randomgive
    permission-message: §4Error:§c You do not have permission to execute this command...
  customrecipes:
    description: Randomgive command
    usage: /<command>
    permission: skyprisoncore.command.customrecipes
    permission-message: §4Error:§c You do not have permission to execute this command...
  namecolour:
    description: namecolour commands
    usage: /<command>
    aliases: [namecolor, multicolour, multicolor, nc]
    permission: skyprisoncore.command.namecolour
    permission-message: §4Error:§c You do not have permission to execute this command...
  rename:
    description: rename commands
    usage: /<command>
    permission: skyprisoncore.command.rename
    permission-message: §4Error:§c You do not have permission to execute this command...
  itemlore:
    description: itemlore commands
    usage: /<command>
    aliases: [ilore]
    permission: skyprisoncore.command.itemlore
    permission-message: §4Error:§c You do not have permission to execute this command...
  news:
    description: news commands
    usage: /<command>
    permission: skyprisoncore.command.news
    permission-message: §4Error:§c You do not have permission to execute this command...
permissions:
  skyprisoncore.command.minereset:
    description: Gives access to minereset

  #
  # Guard Permissions
  #
  skyprisoncore.guard.onduty:
    description: player is on duty when they have this perm
    default: false
  skyprisoncore.showhit:
    description: Shows when a player hits you
  skyprisoncore.contraband.itembypass:
    description: Bypasses Item Removal and that kind of stuff
  #
  # Minigame Permissions
  #
  skyprisoncore.command.sponge:
    description: Gives acess to /sponge
  #
  # Killinfo Permissions
  #
  skyprisoncore.command.killinfo:
    description: Gives access to /killinfo
  skyprisoncore.command.endupgrade:
    description: Gives access to /endupgrade
  skyprisoncore.command.daily:
    description: Gives access to /daily
  skyprisoncore.command.removeitalics:
    description: Gives access to /removeitalics
  skyprisoncore.command.skyplot:
    description: Gives access to /skyplot
  skyprisoncore.command.plotteleport:
    description: Gives access to /plot
  skyprisoncore.command.tags:
    description: Gives access to /tags
  skyprisoncore.command.tags.admin:
    description: Gives access to tags stuff
  skyprisoncore.command.customrecipes:
    description: Gives access to tags stuff
  skyprisoncore.command.namecolour:
    description: Gives access to tags stuff
  skyprisoncore.command.rename:
    description: Gives access to tags stuff
  skyprisoncore.command.itemlore:
    description: Gives access to tags stuff
  skyprisoncore.command.news:
    description: Gives access to tags stuff
