name: $name
authors: [DrakePork, Redhelmet8]
description: $description
version: $version
main: net.skyprison.skyprisoncore.SkyPrisonCore
api-version: "$apiVersion"
website: https://skyprison.net/
depend: [WorldGuard, WorldEdit, PlaceholderAPI, CMI, Parkour, ShopGUIPlus, CoreProtect, PvPManager, AdvancedRegionMarket]
permissions:
  #
  # Guard Permissions
  #
  skyprisoncore.guard.onduty:
    description: player is on duty when they have this perm
    default: false
  skyprisoncore.showhit:
    description: Shows when a player hits you
  skyprisoncore.contraband.itembypass:
    description: Bypasses Item Removal and that kind of stuff
