name: $name
authors: [DrakePork, Redhelmet8]
description: $description
version: $version
main: net.skyprison.skyprisoncore.SkyPrisonCore
api-version: "$apiVersion"
website: https://skyprison.net/
depend: [WorldGuard, WorldEdit, PlaceholderAPI, CMI, Parkour, ShopGUIPlus, CoreProtect, PvPManager, AdvancedRegionMarket, CustomCrafting]
commands:
  transportpass:
    description: bus/train pass
    usage: /<command>
    permission: skyprisoncore.command.transportpass
    permission-message: §4Error:§c You do not have permission to execute this command...
  moneyhistory:
    description: money history
    usage: /<command>
    aliases: [mhistory]
    permission: skyprisoncore.command.moneyhistory
    permission-message: §4Error:§c You do not have permission to execute this command...
  casino:
    description: Buying casino chips
    usage: /<command>
    permission: skyprisoncore.command.casino
    permission-message: §4Error:§c You do not have permission to execute this command...
  tokens:
    description: Token related stuff
    usage: /<command>
    permission: skyprisoncore.command.tokens
    permission-message: §4Error:§c You do not have permission to execute this command...
  token:
    description: Token related stuff
    usage: /<command>
    permission: skyprisoncore.command.tokens
    permission-message: §4Error:§c You do not have permission to execute this command...
  econcheck:
    description: Check the state of the economy
    usage: /<command>
    permission: skyprisoncore.command.econcheck
    permission-message: §4Error:§c You do not have permission to execute this command...
  ignoretp:
    description: Ignore someones tpa requests
    aliases: [tpignore]
    usage: /<command>
    permission: skyprisoncore.command.ignoretp
    permission-message: §4Error:§c You do not have permission to execute this command...
  safezone:
    description: Gives a player a safezone warning
    usage: /<command>
    permission: skyprisoncore.command.safezone
    permission-message: §4Error:§c You do not have permission to execute this command...
  #
  # Contraband Commands
  #
  sword:
    description: Request sword from player
    usage: /<command>
    permission: skyprisoncore.command.sword
    permission-message: §4Error:§c You do not have permission to execute this command...
  bow:
    description: Request bow from player
    usage: /<command>
    permission: skyprisoncore.command.bow
    permission-message: §4Error:§c You do not have permission to execute this command...
  contraband:
    description: Request contraband from player
    usage: /<command>
    permission: skyprisoncore.command.contraband
    permission-message: §4Error:§c You do not have permission to execute this command...
  guardduty:
    description: Enable/disable guardduty
    usage: /<command>
    permission: skyprisoncore.command.guardduty
    permission-message: §4Error:§c You do not have permission to execute this command...
  #
  # Minigame Commands
  #
  sponge:
    description: Sponge Commands
    usage: /<command>
    permission: skyprisoncore.command.sponge
    permission-message: §4Error:§c You do not have permission to execute this command...
  #
  # Teleport Commands
  #
  tokenteleport:
    description: Teleport with tokens wow
    aliases: [tokentp]
    usage: /<command>
    permission: skyprisoncore.command.token
    permission-message: §4Error:§c You do not have permission to execute this command...
  #
  # GUI Commands
  #
  rewards:
    description: Opens the secrets GUI
    usage: /<command>
    aliases: [reward, secret, secrets]
    permission: skyprisoncore.command.secrets
    permission-message: §4Error:§c You do not have permission to execute this command...
  secretfound:
    description: Adds secretfound
    usage: /<command>
    permission: skyprisoncore.command.secretfound
    permission-message: §4Error:§c You do not have permission to execute this command...
  #
  # Bounty Commands
  #
  bounty:
    description: Bounty Commands
    usage: /<command>
    permission: skyprisoncore.command.bounty
    permission-message: §4Error:§c You do not have permission to execute this command...
  #
  # Donation Commands
  #
  donorbulk:
    description: Add a donation
    usage: /<command>
    permission: skyprisoncore.command.donorbulk
    permission-message: §4Error:§c You do not have permission to execute this command...
  donoradd:
    description: Add a donation
    usage: /<command>
    permission: skyprisoncore.command.donoradd
    permission-message: §4Error:§c You do not have permission to execute this command...
  purchases:
    description: Show purchases
    usage: /<command>
    permission: skyprisoncore.command.purchases
    permission-message: §4Error:§c You do not have permission to execute this command...
  endupgrade:
    description: Opens the end upgrade GUI
    usage: /<command>
    permission: skyprisoncore.command.endupgrade
    permission-message: §4Error:§c You do not have permission to execute this command...
  shopban:
    description: Shopban commands
    usage: /<command>
    permission: skyprisoncore.command.shopban
    permission-message: §4Error:§c You do not have permission to execute this command...
  #
  # Killinfo Commands
  #
  killinfo:
    description: Shows info about PvP
    usage: /<command>
    aliases: [killsinfo, killstats, pvpstats]
    permission: skyprisoncore.command.killinfo
    permission-message: §4Error:§c You do not have permission to execute this command...

  dontsell:
    description: Adds/removes an item from the dont sell list
    usage: /<command>
    permission: skyprisoncore.command.dontsell
    permission-message: §4Error:§c You do not have permission to execute this command...
  #
  # Cheese?
  #
  referral:
    description: Give tokens to the guy who reffered you to the server
    usage: /<command>
    aliases: [refer, ref]
    permission: skyprisoncore.command.referral
    permission-message: §4Error:§c You do not have permission to execute this command...
  enchtable:
    description: Open portable enchant table
    usage: /<command>
    aliases: [ench, enchanttable]
    permission: skyprisoncore.command.enchtable
    permission-message: §4Error:§c You do not have permission to execute this command...
  removeitalics:
    description: Removes italics from item
    usage: /<command>
    permission: skyprisoncore.command.removeitalics
    permission-message: §4Error:§c You do not have permission to execute this command...
  bottledexp:
    description: Bottles experience
    usage: /<command>
    aliases: [xpb]
    permission: skyprisoncore.command.bottledexp
    permission-message: §4Error:§c You do not have permission to execute this command...


  firstjointop:
    description: See everyone who has referred you
    usage: /<command>
    aliases: [referlist, reflist]
    permission: skyprisoncore.command.firstjointop
    permission-message: §4Error:§c You do not have permission to execute this command...
  permshop:
    description: See everyone who has referred you
    usage: /<command>
    aliases: [referlist, reflist]
    permission: skyprisoncore.command.permshop
    permission-message: §4Error:§c You do not have permission to execute this command...
  buyback:
    description: Buyback items you sold
    usage: /<command>
    permission: skyprisoncore.command.buyback
    permission-message: §4Error:§c You do not have permission to execute this command...
  daily:
    description: Opens the daily reward GUI
    usage: /<command>
    permission: skyprisoncore.command.daily
    permission-message: §4Error:§c You do not have permission to execute this command...
  fixips:
    description: Opens the daily reward GUI
    usage: /<command>
    permission: skyprisoncore.command.fixips
    permission-message: §4Error:§c You do not have permission to execute this command...
  skyplot:
    description: Opens the daily reward GUI
    usage: /<command>
    permission: skyprisoncore.command.skyplot
    permission-message: §4Error:§c You do not have permission to execute this command...
  plot:
    description: Opens plot TP GUI
    usage: /<command>
    aliases: [plottp, plotteleport]
    permission: skyprisoncore.command.plotteleport
    permission-message: §4Error:§c You do not have permission to execute this command...
  discord:
    description: commands relating to discord
    usage: /<command>
    permission: skyprisoncore.command.discord
    permission-message: §4Error:§c You do not have permission to execute this command...
  bomb:
    description: commands relating to bomb
    usage: /<command>
    permission: skyprisoncore.command.bomb
    permission-message: §4Error:§c You do not have permission to execute this command...
  tags:
    description: Tags command
    usage: /<command>
    permission: skyprisoncore.command.tags
    permission-message: §4Error:§c You do not have permission to execute this command...
  furnace:
    description: Tags command
    usage: /<command>
    permission: skyprisoncore.command.furnace
    permission-message: §4Error:§c You do not have permission to execute this command...
  minereset:
    description: Tags command
    usage: /<command>
    permission: skyprisoncore.command.minereset
    permission-message: §4Error:§c You do not have permission to execute this command...
  randomgive:
    description: Randomgive command
    usage: /<command>
    permission: skyprisoncore.command.randomgive
    permission-message: §4Error:§c You do not have permission to execute this command...
  customrecipes:
    description: Randomgive command
    usage: /<command>
    permission: skyprisoncore.command.customrecipes
    permission-message: §4Error:§c You do not have permission to execute this command...
  claim:
    description: Claim commands
    usage: /<command>
    permission: skyprisoncore.command.claim
    permission-message: §4Error:§c You do not have permission to execute this command...
  namecolour:
    description: Claim commands
    usage: /<command>
    aliases: [namecolor, multicolour, multicolor, nc]
    permission: skyprisoncore.command.namecolour
    permission-message: §4Error:§c You do not have permission to execute this command...
  rename:
    description: Claim commands
    usage: /<command>
    permission: skyprisoncore.command.rename
    permission-message: §4Error:§c You do not have permission to execute this command...
  itemlore:
    description: Claim commands
    usage: /<command>
    aliases: [ilore]
    permission: skyprisoncore.command.itemlore
    permission-message: §4Error:§c You do not have permission to execute this command...
  news:
    description: Claim commands
    usage: /<command>
    permission: skyprisoncore.command.news
    permission-message: §4Error:§c You do not have permission to execute this command...
permissions:
  skyprisoncore.command.discord:
    description: Gives access to discord
  skyprisoncore.command.furnace:
    description: Gives access to discord
  skyprisoncore.command.minereset:
    description: Gives access to discord

  #
  # Guard Permissions
  #
  skyprisoncore.guard.onduty:
    description: player is on duty when they have this perm
    default: false
  skyprisoncore.showhit:
    description: Shows when a player hits you
  skyprisoncore.contraband.itembypass:
    description: Bypasses Item Removal and that kind of stuff
  #
  # Contraband Permissions
  #
  skyprisoncore.command.sword:
    description: Gives access to /sword
  skyprisoncore.command.bow:
    description: Gives access to /bow
  skyprisoncore.command.contraband:
    description: Gives access to /contraband
  skyprisoncore.command.safezone:
    description: Gives access to /safezone

  skyprisoncore.command.guardduty:
    description: Gives access to /guardduty
  #
  # Builder Permissions
  #
  skyprisoncore.builder.onduty:
    description: player is in build mode when they have this perm
    default: false
  #
  # Minigame Permissions
  #
  skyprisoncore.command.sponge:
    description: Gives acess to /sponge
  #
  # Teleport Permissions
  #
  skyprisoncore.command.token:
    description: Gives access to /tokenteleport
  #
  # GUI Permissions
  #
  skyprisoncore.command.secretfound:
    description: Gives access to /secrets
  skyprisoncore.command.secrets:
    description: Gives access to /secrets
  #
  # Bounty Permissions
  #
  skyprisoncore.command.bounty:
    description: Gives access to /bounty commands
  skyprisoncore.command.bounty.bypass:
    description: Players cant bounty you.
  skyprisoncore.command.bounty.silent:
    description: Hides bounty messages
    default: false
  #
  # Donation Permissions
  #
  skyprisoncore.command.donorbulk:
    description: Gives you access to /donorbulk
  skyprisoncore.command.donoradd:
    description: Gives you access to /donoradd
  skyprisoncore.command.purchases:
    description: Gives you access to /purchases
  skyprisoncore.command.purchases.others:
    description: Gives you access to /purchases
  #
  # Killinfo Permissions
  #
  skyprisoncore.command.killinfo:
    description: Gives access to /killinfo
  #
  # Referral
  #
  skyprisoncore.command.referrallist:
    description: Gives access to /referrallist
  skyprisoncore.command.referral:
    description: Gives access to /referral

  skyprisoncore.command.firstjointop:
    description: Gives access to /firstjointop
  skyprisoncore.command.permshop:
    description: Gives access to /permshop
  skyprisoncore.command.econcheck:
    description: Gives access to /econcheck
  skyprisoncore.command.buyback:
    description: Gives access to /buyback
  skyprisoncore.command.dontsell:
    description: Gives access to /dontsell
  skyprisoncore.command.endupgrade:
    description: Gives access to /endupgrade
  skyprisoncore.command.daily:
    description: Gives access to /daily
  skyprisoncore.command.shopban:
    description: Gives access to /shopban
  skyprisoncore.command.fixips:
    description: Gives access to /shopban
  skyprisoncore.command.enchtable:
    description: Gives access to /enchtable
  skyprisoncore.command.removeitalics:
    description: Gives access to /removeitalics
  skyprisoncore.command.bottledexp:
    description: Gives access to /removeitalics
  skyprisoncore.command.bottledexp.tier1:
    description: Gives access to 10,000 XP /xpb
  skyprisoncore.command.bottledexp.tier2:
    description: Gives access to ANY XP /xpb
  skyprisoncore.command.bottledexp.tier3:
    description: Gives access to /xpb <exp> <amount of bottles>
  skyprisoncore.command.skyplot:
    description: Gives access to /skyplot
  skyprisoncore.command.plotteleport:
    description: Gives access to /plot
  skyprisoncore.command.tokens:
    description: Gives access to /tokens
  skyprisoncore.command.tokens.admin:
    description: Gives access to admin tokens commands
  skyprisoncore.command.casino:
    description: Gives access to /casino
  skyprisoncore.command.transportpass:
    description: Gives access to /transportpass
  skyprisoncore.command.moneyhistory:
    description: Gives access to /moneyhistory
  skyprisoncore.command.tags:
    description: Gives access to /tags
  skyprisoncore.command.tags.admin:
    description: Gives access to tags stuff
  skyprisoncore.command.bomb:
    description: Gives access to tags stuff
  skyprisoncore.command.customrecipes:
    description: Gives access to tags stuff
  skyprisoncore.command.claim:
    description: Gives access to tags stuff
  skyprisoncore.command.namecolour:
    description: Gives access to tags stuff
  skyprisoncore.command.rename:
    description: Gives access to tags stuff
  skyprisoncore.command.itemlore:
    description: Gives access to tags stuff
  skyprisoncore.command.news:
    description: Gives access to tags stuff
